"""add auth columns

Revision ID: a081e9ed2211
Revises: 
Create Date: 2026-05-01 22:05:00.134403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a081e9ed2211'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.add_column('transactions', sa.Column('description', sa.String(), server_default='Transferencia', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'description')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_column('accounts', 'hashed_password')
    op.drop_column('accounts', 'email')
    # ### end Alembic commands ###
